version: '3.8'

services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    hostname: transmission
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
#      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
#      - TRANSMISSION_WEB_HOME=/kettu/
      - USER=aurick #optional
      - PASS=aurick #optional
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - config:/config
#      - /media/usb2:/downloads
      - /media/usb1/torrent:/downloads/complete
      - /media/usb2:/downloads/incomplete
#      - path to watch folder:/watch

volumes:
  config: